### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by robertbastian** [Berrysoft/language-matcher#3]
Could you elaborate on "the language matching data in the JSON data of CLDR is broken"? Is there an issue tracking this?

**Comment by Berrysoft** [comment]
See #1 .

**Comment by Berrysoft** [comment]
I don't remember if I've opened an issue to CLDR repo. I think, if there are people in the ICU team going to implement the language matcher, they will find that the JSON data is broken; if there are no people going to do this, there should be few people want this, so this problem is not important:)
